# Generated by Django 5.1.7 on 2026-04-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='capacidade_producao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='oe_relevance_params',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
